ALTER TABLE "FileFolder" ALTER COLUMN "projectId" DROP NOT NULL;
ALTER TABLE "FileAsset" ALTER COLUMN "projectId" DROP NOT NULL;
ALTER TABLE "FileUploadSession" ALTER COLUMN "projectId" DROP NOT NULL;
ALTER TABLE "FileShare" ALTER COLUMN "projectId" DROP NOT NULL;
