import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { teamAccess } from "@/lib/team-api";

function shanghaiDay(offset=0){const local=new Date(Date.now()+8*3600_000);local.setUTCHours(0,0,0,0);local.setUTCDate(local.getUTCDate()+offset);return new Date(local.getTime()-8*3600_000);}
export async function GET(request:NextRequest,{params}:{params:Promise<{teamId:string}>}){
 const {teamId}=await params;const access=await teamAccess(request,teamId);if("error" in access)return access.error;if(access.membership.role==="GUEST")return NextResponse.json({error:"访客不能查看全员效能"},{status:403});
 const url=new URL(request.url),memberId=url.searchParams.get("memberId")||undefined, today=shanghaiDay(), tomorrow=shanghaiDay(1), trendStart=shanghaiDay(-29);const localNow=new Date(Date.now()+8*3600_000),monthStart=new Date(Date.UTC(localNow.getUTCFullYear(),localNow.getUTCMonth(),1)-8*3600_000);
 const members=await prisma.teamMember.findMany({where:{teamId,role:{not:"GUEST"},...(memberId?{userId:memberId}:{})},include:{user:{select:{id:true,name:true,avatarColor:true}}}});const ids=members.map(x=>x.userId),projects=await prisma.project.findMany({where:{teamId},select:{id:true}}),projectIds=projects.map(x=>x.id);
 const [tasks,acceptances,objectives]=await Promise.all([prisma.task.findMany({where:{projectId:{in:projectIds},completedAt:{gte:trendStart},OR:[{assigneeId:{in:ids}},{coordinatorId:{in:ids}}]},select:{assigneeId:true,coordinatorId:true,completedAt:true}}),prisma.acceptance.findMany({where:{reviewerId:{in:ids},createdAt:{gte:trendStart},task:{projectId:{in:projectIds}}},select:{reviewerId:true,createdAt:true}}),prisma.teamObjective.findMany({where:{teamId,status:{in:["ACTIVE","AT_RISK"]}},include:{keyResults:true}})]);
 const days=Array.from({length:30},(_,i)=>{const date=shanghaiDay(i-29);return{date:date.toLocaleDateString("sv-SE",{timeZone:"Asia/Shanghai"}),delivery:0,coordination:0,acceptance:0}}),byDay=new Map(days.map(x=>[x.date,x]));
 const counts=(from:Date,to?:Date)=>{const inRange=(d:Date)=>d>=from&&(!to||d<to);return{delivery:tasks.filter(x=>x.assigneeId&&inRange(x.completedAt!)).length,coordination:tasks.filter(x=>x.coordinatorId&&inRange(x.completedAt!)).length,acceptance:acceptances.filter(x=>inRange(x.createdAt)).length}};
 for(const task of tasks){const d=task.completedAt!.toLocaleDateString("sv-SE",{timeZone:"Asia/Shanghai"}),row=byDay.get(d);if(row){if(task.assigneeId)row.delivery++;if(task.coordinatorId)row.coordination++;}}for(const item of acceptances){const row=byDay.get(item.createdAt.toLocaleDateString("sv-SE",{timeZone:"Asia/Shanghai"}));if(row)row.acceptance++;}
 const memberStats=members.map(m=>({userId:m.userId,name:m.user.name,avatarColor:m.user.avatarColor,month:{delivery:tasks.filter(x=>x.assigneeId===m.userId&&x.completedAt!>=monthStart).length,coordination:tasks.filter(x=>x.coordinatorId===m.userId&&x.completedAt!>=monthStart).length,acceptance:acceptances.filter(x=>x.reviewerId===m.userId&&x.createdAt>=monthStart).length}}));
 const ongoing=await prisma.task.count({where:{projectId:{in:projectIds},status:{in:["IN_PROGRESS","PENDING_ACCEPTANCE","NEEDS_CHANGES","ACCEPTED"]},...(memberId?{OR:[{assigneeId:memberId},{coordinatorId:memberId},{acceptorId:memberId}]}:{})}}),overdue=await prisma.task.count({where:{projectId:{in:projectIds},dueAt:{lt:new Date()},status:{not:"DONE"},...(memberId?{OR:[{assigneeId:memberId},{coordinatorId:memberId},{acceptorId:memberId}]}:{})}});
 const kr=objectives.flatMap(x=>x.keyResults),okrHealth=kr.length?Math.round(kr.reduce((s,x)=>s+Math.min(100,x.targetValue?x.currentValue/x.targetValue*100:0),0)/kr.length):0;
 return NextResponse.json({today:counts(today,tomorrow),month:counts(monthStart),ongoing,overdue,okrHealth,trend:days,members:memberStats});
}
