import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { fileUser, folderMoveCreatesCycle, projectFileAccess } from "@/lib/file-auth";

export async function PATCH(request: Request, { params }: { params: Promise<{ folderId: string }> }) {
  const user = await fileUser(request); if (!user) return NextResponse.json({ error: "请先登录" }, { status: 401 }); const { folderId } = await params;
  const input = z.object({ name: z.string().trim().min(1).max(120).optional(), parentId: z.string().nullable().optional() }).safeParse(await request.json()); if (!input.success) return NextResponse.json({ error: input.error.issues[0]?.message }, { status: 400 });
  const folder = await prisma.fileFolder.findUnique({ where: { id: folderId } }); if (!folder) return NextResponse.json({ error: "文件夹不存在" }, { status: 404 }); if (!(await projectFileAccess(user.id, folder.projectId)).canManage && folder.creatorId !== user.id) return NextResponse.json({ error: "没有修改文件夹的权限" }, { status: 403 });
  const parent = input.data.parentId ? await prisma.fileFolder.findFirst({ where: { id: input.data.parentId, projectId: folder.projectId, deletedAt: null } }) : null; if (input.data.parentId && !parent) return NextResponse.json({ error: "目标文件夹不存在" }, { status: 404 }); if (folderMoveCreatesCycle(folder.id, folder.path, parent)) return NextResponse.json({ error: "不能将文件夹移动到自身或其子目录" }, { status: 400 });
  const name = input.data.name || folder.name, path = `${parent?.path || ""}/${name}`; const duplicate = await prisma.fileFolder.findFirst({ where: { projectId: folder.projectId, parentId: input.data.parentId === undefined ? folder.parentId : input.data.parentId, name, deletedAt: null, id: { not: folder.id } } }); if (duplicate) return NextResponse.json({ error: "目标位置已有同名文件夹" }, { status: 409 });
  const descendants = await prisma.fileFolder.findMany({ where: { projectId: folder.projectId, path: { startsWith: `${folder.path}/` } }, select: { id: true, path: true } }); await prisma.$transaction([prisma.fileFolder.update({ where: { id: folder.id }, data: { name, parentId: input.data.parentId === undefined ? folder.parentId : input.data.parentId, path } }), ...descendants.map(child => prisma.fileFolder.update({ where: { id: child.id }, data: { path: `${path}${child.path.slice(folder.path.length)}` } }))]); return NextResponse.json({ ok: true });
}
export async function DELETE(request: Request, { params }: { params: Promise<{ folderId: string }> }) {
  const user = await fileUser(request); if (!user) return NextResponse.json({ error: "请先登录" }, { status: 401 }); const { folderId } = await params, folder = await prisma.fileFolder.findUnique({ where: { id: folderId } }); if (!folder) return NextResponse.json({ error: "文件夹不存在" }, { status: 404 }); if (!(await projectFileAccess(user.id, folder.projectId)).canManage && folder.creatorId !== user.id) return NextResponse.json({ error: "没有删除文件夹的权限" }, { status: 403 }); const descendants = await prisma.fileFolder.findMany({ where: { projectId: folder.projectId, OR: [{ id: folder.id }, { path: { startsWith: `${folder.path}/` } }] }, select: { id: true } }), ids = descendants.map(item => item.id), now = new Date(); await prisma.$transaction([prisma.fileAsset.updateMany({ where: { folderId: { in: ids }, deletedAt: null }, data: { deletedAt: now } }), prisma.fileFolder.updateMany({ where: { id: { in: ids } }, data: { deletedAt: now } })]); return NextResponse.json({ ok: true });
}
