"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { FolderKanban, LoaderCircle, MoreHorizontal, Plus, Users, X } from "lucide-react";

type Project={id:string;code:string;name:string;description:string;status:string;team:{id:string;name:string};memberCount:number;taskCount:number};
type Team={id:string;name:string};

export function ProjectsPage(){
  const [projects,setProjects]=useState<Project[]>([]),[teams,setTeams]=useState<Team[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);try{const response=await fetch("/api/projects");const body=await response.json();if(!response.ok)throw new Error(body.error||"加载失败");setProjects(body.projects);setTeams(body.teams);}catch(e){setError(e instanceof Error?e.message:"加载失败");}finally{setLoading(false);}},[]);
  useEffect(()=>{let active=true;fetch("/api/projects").then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error||"加载失败");if(active){setProjects(body.projects);setTeams(body.teams);}}).catch(e=>{if(active)setError(e instanceof Error?e.message:"加载失败");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
  return <div className="space-y-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="text-2xl font-bold tracking-tight">项目管理</h2><p className="mt-1 text-sm text-slate-500">项目归属于团队，成员仍需单独授予项目权限</p></div><button disabled={!teams.length} onClick={()=>setOpen(true)} className="primary-button disabled:opacity-50"><Plus size={17}/>新建项目</button></div>{error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}{loading?<div className="grid min-h-72 place-items-center"><LoaderCircle className="animate-spin text-blue-600" size={28}/></div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{projects.map(project=><article key={project.id} className="card p-5"><div className="flex items-start"><span className="grid size-11 place-items-center rounded-xl bg-blue-50 text-blue-600"><FolderKanban size={21}/></span><button className="ml-auto text-slate-400"><MoreHorizontal size={19}/></button></div><div className="mt-5 flex items-center gap-2"><h3 className="font-semibold">{project.name}</h3><span className="rounded bg-slate-100 px-1.5 py-0.5 text-[10px] text-slate-500">{project.code}</span></div><p className="mt-1 text-xs text-blue-600">{project.team.name}</p><p className="mt-3 line-clamp-2 min-h-10 text-sm text-slate-500">{project.description||"暂无项目说明"}</p><div className="mt-4 flex gap-4 border-t border-slate-100 pt-4 text-xs text-slate-500"><span className="flex items-center gap-1"><Users size={13}/>{project.memberCount} 位成员</span><span>{project.taskCount} 个任务</span></div></article>)}</div>}{!loading&&!projects.length&&<div className="card p-12 text-center text-sm text-slate-500">还没有可访问的项目</div>}{open&&<CreateProject teams={teams} onClose={()=>setOpen(false)} onCreated={async()=>{setOpen(false);await load();}}/>}</div>;
}

function CreateProject({teams,onClose,onCreated}:{teams:Team[];onClose:()=>void;onCreated:()=>void}){const [teamId,setTeamId]=useState(teams[0]?.id||""),[name,setName]=useState(""),[code,setCode]=useState(""),[description,setDescription]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState("");async function submit(event:FormEvent){event.preventDefault();setLoading(true);try{const response=await fetch("/api/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({teamId,name,code,description})});const body=await response.json();if(!response.ok)throw new Error(body.error||"创建失败");onCreated();}catch(e){setError(e instanceof Error?e.message:"创建失败");setLoading(false);}}return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/30 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl"><div className="mb-5 flex items-center"><h3 className="text-lg font-semibold">新建项目</h3><button type="button" onClick={onClose} className="ml-auto p-2 text-slate-400"><X size={19}/></button></div><div className="space-y-4"><label className="block"><span className="mb-2 block text-sm font-medium">所属团队</span><select className="field" value={teamId} onChange={e=>setTeamId(e.target.value)}>{teams.map(team=><option key={team.id} value={team.id}>{team.name}</option>)}</select></label><label className="block"><span className="mb-2 block text-sm font-medium">项目名称</span><input className="field" value={name} onChange={e=>setName(e.target.value)} placeholder="例如：移动端重构"/></label><label className="block"><span className="mb-2 block text-sm font-medium">项目标识</span><input className="field uppercase" value={code} onChange={e=>setCode(e.target.value.replace(/[^A-Za-z0-9_-]/g,"").slice(0,12))} placeholder="例如：MOBILE"/></label><label className="block"><span className="mb-2 block text-sm font-medium">项目说明（可选）</span><textarea className="min-h-20 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-500" value={description} onChange={e=>setDescription(e.target.value)}/></label>{error&&<div className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="secondary-button">取消</button><button disabled={loading} className="primary-button">{loading?<LoaderCircle className="animate-spin" size={17}/>:<Plus size={17}/>}创建项目</button></div></div></form></div>}
