"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, Check, Clock3, Copy, KeyRound, Laptop, LoaderCircle, Target, UserRound, X } from "lucide-react";

type Member = { id: string; userId: string; name: string; phone: string; avatarColor: string; roleLabel: string; title: string | null; responsibility: string | null; bio: string | null };
type Team = { id: string; name: string; currentRole: string; permissions: { canManage: boolean }; members: Member[]; viewerUserId: string };
type Usage = { totalTokens: number | string; sessions: number };
type Statistics = {
  contribution: { requirementsProposed: number; requirementsClosed: number; averageRequirementHours: number | null; weeklyCompletedTasks: number; pendingAcceptance: number; currentTasks: Array<{ id: string; code: string; title: string; status: string; project: { name: string } }> };
  usage: { today: Usage; week: Usage; month: Usage; all: Usage; scopeLabel: string; details: null | Array<{ tool: string; inputTokens: number | string; outputTokens: number | string; cacheTokens: number | string; reasoningTokens: number | string }>; devices: Array<{ id?: string; name?: string; clientVersion?: string; lastSeenAt: string | null; lastStatus: string; lastError?: string | null; revokedAt?: string | null }> };
};

async function json<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, init); const body = await response.json(); if (!response.ok) throw new Error(body.error || "请求失败"); return body; }
function numeric(value: number | string) { return typeof value === "number" ? value : Number(value); }
function compact(value: number | string) { return new Intl.NumberFormat("zh-CN", { notation: "compact", maximumFractionDigits: 2 }).format(numeric(value)); }
function dateTime(value: string | null) { return value ? new Date(value).toLocaleString("zh-CN", { timeZone: "Asia/Shanghai" }) : "尚未上报"; }
function duration(hours: number | null) { return hours === null ? "暂无数据" : hours < 24 ? `${hours} 小时` : `${(hours / 24).toFixed(1)} 天`; }

export function TeamPersonalInfo({ team }: { team: Team }) {
  const member = team.members.find((item) => item.userId === team.viewerUserId);
  const [stats, setStats] = useState<Statistics | null>(null), [error, setError] = useState(""), [registration, setRegistration] = useState<{ installCommand: string; expiresAt: string } | null>(null);
  const load = useCallback(async () => { if (!member) return; try { setStats(await json(`/api/teams/${team.id}/members/${member.id}/statistics`)); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "加载失败"); } }, [member, team.id]);
  useEffect(() => {
    if (!member) return;
    let active = true;
    json<Statistics>(`/api/teams/${team.id}/members/${member.id}/statistics`).then((data) => { if (active) { setStats(data); setError(""); } }).catch((cause) => { if (active) setError(cause instanceof Error ? cause.message : "加载失败"); });
    return () => { active = false; };
  }, [member, team.id]);
  const tools = useMemo(() => { const values = new Map<string, number>(); for (const row of stats?.usage.details || []) values.set(row.tool, (values.get(row.tool) || 0) + numeric(row.inputTokens) + numeric(row.outputTokens) + numeric(row.cacheTokens) + numeric(row.reasoningTokens)); return [...values]; }, [stats]);
  if (!member) return <div className="rounded-xl bg-amber-50 p-4 text-sm text-amber-700">当前账户不在团队成员列表中。</div>;
  if (team.currentRole === "GUEST") return <div className="rounded-xl bg-slate-100 p-5 text-sm text-slate-500">访客不可查看团队成员个人统计。</div>;
  if (!stats) return <div className="grid min-h-64 place-items-center">{error || <LoaderCircle className="animate-spin text-blue-600" />}</div>;
  return <div className="space-y-5">
    {error && <div className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
    <section className="card p-5 sm:p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><span className="grid size-20 place-items-center rounded-2xl text-2xl font-bold text-white" style={{ backgroundColor: member.avatarColor }}>{member.name.slice(-1)}</span><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-xl font-bold">{member.name}</h3><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs text-blue-700">{member.roleLabel}</span></div><p className="mt-1 text-sm text-slate-500">{member.title || "暂未设置团队岗位"} · {member.phone}</p><p className="mt-2 text-sm text-slate-500">{team.name}</p></div></div><div className="mt-5 grid gap-4 border-t border-slate-100 pt-5 md:grid-cols-2"><Info label="团队职责" value={member.responsibility || "暂未设置"}/><Info label="个人介绍" value={member.bio || "暂未设置"}/></div></section>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="提出需求" value={stats.contribution.requirementsProposed} icon={Target}/><Metric label="闭环需求" value={stats.contribution.requirementsClosed} icon={Check}/><Metric label="平均闭环时间" value={duration(stats.contribution.averageRequirementHours)} icon={Clock3}/><Metric label="本周完成" value={stats.contribution.weeklyCompletedTasks} icon={Activity}/><Metric label="待我验收" value={stats.contribution.pendingAcceptance} icon={UserRound}/></div>
    <section className="card overflow-hidden"><div className="border-b border-slate-100 p-5"><h4 className="font-semibold">当前团队任务</h4><p className="mt-1 text-xs text-slate-400">只统计归属于当前团队的项目</p></div>{stats.contribution.currentTasks.length ? <div className="divide-y divide-slate-100">{stats.contribution.currentTasks.map((task) => <div key={task.id} className="flex items-center gap-3 p-4"><div><p className="text-sm font-medium">{task.title}</p><p className="text-xs text-slate-400">{task.project.name} · {task.code}</p></div><span className="ml-auto rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-600">{task.status}</span></div>)}</div> : <div className="p-10 text-center text-sm text-slate-400">当前没有未完成任务</div>}</section>
    <section className="card p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start"><div><h4 className="font-semibold">AI Token 用量</h4><p className="mt-1 text-xs text-amber-600">{stats.usage.scopeLabel}</p></div><button onClick={async () => { try { setRegistration(await json("/api/usage-collectors/registrations", { method: "POST" })); } catch (cause) { setError(cause instanceof Error ? cause.message : "生成失败"); } }} className="primary-button sm:ml-auto"><KeyRound size={16}/>接入 Token 统计</button></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-4">{[["今日",stats.usage.today],["本周",stats.usage.week],["本月",stats.usage.month],["累计",stats.usage.all]].map(([label,usage]) => <UsageMetric key={label as string} label={label as string} usage={usage as Usage}/>)}</div>
      <div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-slate-100 p-4"><p className="text-sm font-medium">工具分布（近30日）</p>{tools.length ? <div className="mt-4 space-y-3">{tools.map(([tool,total]) => <div key={tool}><div className="flex text-xs"><span>{tool === "CODEX" ? "Codex" : "Claude Code"}</span><span className="ml-auto">{compact(total)}</span></div><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-500" style={{ width: `${Math.max(4,total/Math.max(...tools.map(([,value])=>value))*100)}%` }}/></div></div>)}</div> : <p className="mt-6 text-sm text-slate-400">接入采集器后显示用量趋势</p>}</div><div className="rounded-xl border border-slate-100 p-4"><p className="text-sm font-medium">采集设备</p><div className="mt-3 space-y-2">{stats.usage.devices.length ? stats.usage.devices.map((device,index) => <div key={device.id || index} className="flex items-center gap-3 rounded-lg bg-slate-50 p-3"><Laptop size={17} className="text-blue-500"/><div className="min-w-0"><p className="truncate text-sm">{device.name || "采集设备"}</p><p className="text-xs text-slate-400">{device.lastStatus} · {dateTime(device.lastSeenAt)}{device.clientVersion ? ` · v${device.clientVersion}` : ""}</p>{device.lastError && <p className="mt-1 text-xs text-rose-500">{device.lastError}</p>}</div>{device.id && !device.revokedAt && <button onClick={async()=>{await json(`/api/usage-collectors/devices/${device.id}`,{method:"DELETE"});await load();}} className="ml-auto text-xs text-rose-600">撤销</button>}</div>) : <p className="py-4 text-sm text-slate-400">尚未接入采集设备</p>}</div></div></div>
    </section>
    {registration && <Registration command={registration.installCommand} expiresAt={registration.expiresAt} close={()=>setRegistration(null)}/>}
  </div>;
}

function Info({label,value}:{label:string;value:string}) { return <div><p className="text-xs text-slate-400">{label}</p><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-slate-600">{value}</p></div>; }
function Metric({label,value,icon:Icon}:{label:string;value:string|number;icon:typeof Target}) { return <div className="card p-4"><div className="flex items-center gap-2 text-slate-400"><Icon size={16}/><span className="text-xs">{label}</span></div><p className="mt-3 text-xl font-bold">{value}</p></div>; }
function UsageMetric({label,usage}:{label:string;usage:Usage}) { return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-400">{label}</p><p className="mt-2 text-xl font-bold text-slate-800">{compact(usage.totalTokens)}</p><p className="mt-1 text-[11px] text-slate-400">{usage.sessions} 个会话</p></div>; }
function Registration({command,expiresAt,close}:{command:string;expiresAt:string;close:()=>void}) { const [copied,setCopied]=useState(false); return <div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/40 p-4 backdrop-blur-sm"><button aria-label="关闭" className="absolute inset-0" onClick={close}/><section className="relative w-full max-w-xl rounded-2xl bg-white p-5 shadow-2xl"><div className="flex items-center"><h3 className="text-lg font-semibold">接入 Token 统计</h3><button onClick={close} className="ml-auto text-slate-400"><X size={19}/></button></div><p className="mt-4 text-sm leading-6 text-slate-600">在 Windows PowerShell 中执行以下命令。注册码10分钟内有效且只能使用一次。</p><div className="mt-4 flex items-start gap-2 rounded-xl bg-slate-950 p-3 text-slate-100"><code className="min-w-0 flex-1 break-all text-xs leading-5">{command}</code><button onClick={async()=>{await navigator.clipboard.writeText(command);setCopied(true)}} className="rounded-lg bg-white/10 p-2">{copied?<Check size={16}/>:<Copy size={16}/>}</button></div><p className="mt-3 text-xs text-slate-400">有效期至 {dateTime(expiresAt)}。不会上传提示词、代码、文件内容或密钥。</p></section></div>; }
