"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { Building2, Check, ChevronRight, Clipboard, FolderKanban, Link2, LoaderCircle, Plus, RefreshCw, Search, Settings2, ShieldCheck, Trash2, UserPlus, Users, X } from "lucide-react";

type Role = "OWNER" | "ADMIN" | "MEMBER" | "GUEST";
type TeamSummary = { id:string; name:string; description:string|null; role:Role; roleLabel:string; memberCount:number; projectCount:number };
type TeamDetail = TeamSummary & {
  currentRole:Role; currentRoleLabel:string; createdAt:string;
  permissions:{canManage:boolean;canInviteAdmin:boolean;canCreateProject:boolean};
  members:Array<{id:string;userId:string;name:string;phone:string;avatarColor:string;role:Role;roleLabel:string;joinedAt:string}>;
  projects:Array<{id:string;code:string;name:string;description:string;status:string;memberCount:number;taskCount:number;updatedAt:string}>;
  invites:Array<{id:string;prefix:string;url:string|null;role:Role;roleLabel:string;maxUses:number;useCount:number;expiresAt:string;revokedAt:string|null;createdAt:string;createdBy:string}>;
};

const roleClass:Record<Role,string>={OWNER:"bg-orange-50 text-orange-700",ADMIN:"bg-violet-50 text-violet-700",MEMBER:"bg-emerald-50 text-emerald-700",GUEST:"bg-slate-100 text-slate-600"};
const tabs=[{id:"overview",label:"概览"},{id:"projects",label:"团队项目"},{id:"members",label:"成员"},{id:"invites",label:"待定邀请"},{id:"roles",label:"角色与权限"},{id:"settings",label:"团队设置"}] as const;

async function jsonRequest<T>(url:string, init?:RequestInit):Promise<T>{
  const response=await fetch(url,{...init,headers:{"Content-Type":"application/json",...(init?.headers||{})}});
  const body=await response.json();
  if(!response.ok) throw new Error(body.error||"操作失败，请稍后重试");
  return body;
}

async function copyText(value:string){
  try{
    if(!navigator.clipboard?.writeText)throw new Error("clipboard unavailable");
    await navigator.clipboard.writeText(value);
  }catch{
    const textarea=document.createElement("textarea");
    textarea.value=value;textarea.setAttribute("readonly","");textarea.style.position="fixed";textarea.style.opacity="0";
    document.body.appendChild(textarea);textarea.select();
    const copied=document.execCommand("copy");textarea.remove();
    if(!copied)throw new Error("浏览器未允许复制，请手动选择链接复制");
  }
}

export function TeamManagement({teamId}:{teamId?:string}){
  return teamId?<TeamDetailPage teamId={teamId}/>:<TeamList/>;
}

function TeamList(){
  const router=useRouter();
  const [teams,setTeams]=useState<TeamSummary[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[error,setError]=useState("");
  useEffect(()=>{let active=true;jsonRequest<{teams:TeamSummary[]}>("/api/teams").then(data=>{if(active)setTeams(data.teams);}).catch(e=>{if(active)setError(e instanceof Error?e.message:"加载失败");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
  return <div className="space-y-6">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="text-2xl font-bold tracking-tight">团队管理</h2><p className="mt-1 text-sm text-slate-500">创建团队、组织项目，并管理成员与团队权限</p></div><button onClick={()=>setOpen(true)} className="primary-button"><Plus size={17}/>新建团队</button></div>
    {error&&<ErrorBox message={error}/>} {loading?<Loading/>:teams.length?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{teams.map(team=><Link href={`/teams/${team.id}`} key={team.id} className="card group p-5 transition hover:-translate-y-0.5 hover:border-blue-200 hover:shadow-md"><div className="flex items-start"><span className="grid size-11 place-items-center rounded-xl bg-blue-50 text-blue-600"><Users size={21}/></span><span className={`ml-auto rounded-full px-2.5 py-1 text-xs font-medium ${roleClass[team.role]}`}>{team.roleLabel}</span></div><h3 className="mt-5 font-semibold group-hover:text-blue-700">{team.name}</h3><p className="mt-1 line-clamp-2 min-h-10 text-sm leading-5 text-slate-500">{team.description||"暂无团队介绍"}</p><div className="mt-5 flex items-center gap-5 border-t border-slate-100 pt-4 text-xs text-slate-500"><span className="flex items-center gap-1.5"><Users size={14}/>{team.memberCount} 位成员</span><span className="flex items-center gap-1.5"><FolderKanban size={14}/>{team.projectCount} 个项目</span><ChevronRight className="ml-auto text-slate-300 group-hover:text-blue-500" size={17}/></div></Link>)}</div>:<Empty title="还没有团队" description="创建第一个团队，开始组织项目和协作成员。" action={<button onClick={()=>setOpen(true)} className="primary-button"><Plus size={17}/>新建团队</button>}/>} 
    {open&&<CreateTeamModal onClose={()=>setOpen(false)} onCreated={(id)=>router.push(`/teams/${id}`)}/>} 
  </div>;
}

function CreateTeamModal({onClose,onCreated}:{onClose:()=>void;onCreated:(id:string)=>void}){
  const [name,setName]=useState(""),[description,setDescription]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false);
  async function submit(event:FormEvent){event.preventDefault();setLoading(true);setError("");try{const data=await jsonRequest<{team:{id:string}}>("/api/teams",{method:"POST",body:JSON.stringify({name,description})});onCreated(data.team.id);}catch(e){setError(e instanceof Error?e.message:"创建失败");setLoading(false);}}
  return <Modal title="新建团队" onClose={onClose}><form onSubmit={submit} className="space-y-4"><Field label="团队名称"><input autoFocus className="field" value={name} onChange={e=>setName(e.target.value)} placeholder="例如：产品研发团队" maxLength={40}/></Field><Field label="团队介绍（可选）"><textarea className="min-h-24 w-full resize-none rounded-xl border border-[#dfe5ee] bg-white p-3 outline-none focus:border-blue-500" value={description} onChange={e=>setDescription(e.target.value)} placeholder="简单说明团队负责的业务和协作范围" maxLength={200}/></Field>{error&&<ErrorBox message={error}/>}<div className="flex justify-end gap-2 pt-2"><button type="button" onClick={onClose} className="secondary-button">取消</button><button disabled={loading} className="primary-button">{loading?<LoaderCircle className="animate-spin" size={17}/>:<Plus size={17}/>}创建团队</button></div></form></Modal>;
}

function TeamDetailPage({teamId}:{teamId:string}){
  const [team,setTeam]=useState<TeamDetail|null>(null),[tab,setTab]=useState<typeof tabs[number]["id"]>("overview"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[inviteOpen,setInviteOpen]=useState(false);
  const load=useCallback(async()=>{try{const data=await jsonRequest<{team:TeamDetail}>(`/api/teams/${teamId}`);setTeam(data.team);setError("");}catch(e){setError(e instanceof Error?e.message:"加载失败");}},[teamId]);
  useEffect(()=>{let active=true;jsonRequest<{team:TeamDetail}>(`/api/teams/${teamId}`).then(data=>{if(active){setTeam(data.team);setError("");}}).catch(e=>{if(active)setError(e instanceof Error?e.message:"加载失败");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[teamId]);
  if(loading)return <Loading/>; if(!team)return <ErrorBox message={error||"团队不存在"}/>;
  return <div className="space-y-5">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs text-slate-400"><Link href="/teams" className="hover:text-blue-600">团队管理</Link><ChevronRight size={13}/><span>{team.name}</span></div><div className="flex flex-wrap items-center gap-3"><h2 className="text-2xl font-bold tracking-tight">{team.name}</h2><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${roleClass[team.currentRole]}`}>{team.currentRoleLabel}</span></div><p className="mt-1 text-sm text-slate-500">{team.description||"暂无团队介绍"}</p></div>{team.permissions.canManage&&<button onClick={()=>setInviteOpen(true)} className="primary-button"><UserPlus size={17}/>邀请成员</button>}</div>
    {error&&<ErrorBox message={error}/>}<div className="scrollbar-none flex gap-1 overflow-x-auto border-b border-[#e4eaf2]">{tabs.map(item=><button key={item.id} onClick={()=>setTab(item.id)} className={`whitespace-nowrap border-b-2 px-4 py-3 text-sm font-medium ${tab===item.id?"border-blue-600 text-blue-700":"border-transparent text-slate-500 hover:text-slate-900"}`}>{item.label}</button>)}</div>
    {tab==="overview"&&<Overview team={team} onTab={setTab}/>} {tab==="projects"&&<Projects team={team}/>} {tab==="members"&&<Members team={team} reload={load}/>} {tab==="invites"&&<Invites team={team} reload={load} onNew={()=>setInviteOpen(true)}/>} {tab==="roles"&&<Roles/>} {tab==="settings"&&<Settings team={team}/>} 
    {inviteOpen&&<InviteModal team={team} onClose={()=>setInviteOpen(false)} onCreated={()=>void load()}/>} 
  </div>;
}

function Overview({team,onTab}:{team:TeamDetail;onTab:(tab:"projects"|"members"|"invites")=>void}){
  const activeInvites=team.invites.filter(x=>!x.revokedAt&&new Date(x.expiresAt)>new Date()&&x.useCount<x.maxUses).length;
  return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-3">{[{label:"团队成员",value:team.members.length,icon:Users,tab:"members" as const},{label:"可访问项目",value:team.projects.length,icon:FolderKanban,tab:"projects" as const},{label:"有效邀请",value:activeInvites,icon:Link2,tab:"invites" as const}].map(item=><button onClick={()=>onTab(item.tab)} key={item.label} className="card flex items-center gap-4 p-5 text-left hover:border-blue-200"><span className="grid size-11 place-items-center rounded-xl bg-blue-50 text-blue-600"><item.icon size={20}/></span><span><b className="text-2xl">{item.value}</b><span className="mt-0.5 block text-sm text-slate-500">{item.label}</span></span><ChevronRight className="ml-auto text-slate-300" size={18}/></button>)}</div><div className="grid gap-5 lg:grid-cols-2"><section className="card p-5"><h3 className="font-semibold">最近加入的成员</h3><div className="mt-4 space-y-3">{team.members.slice(0,5).map(member=><div key={member.id} className="flex items-center gap-3"><Avatar name={member.name} color={member.avatarColor}/><div><p className="text-sm font-medium">{member.name}</p><p className="text-xs text-slate-400">{member.phone}</p></div><span className={`ml-auto rounded-full px-2.5 py-1 text-xs ${roleClass[member.role]}`}>{member.roleLabel}</span></div>)}</div></section><section className="card p-5"><h3 className="font-semibold">团队项目</h3><div className="mt-4 space-y-3">{team.projects.slice(0,5).map(project=><div key={project.id} className="rounded-xl border border-slate-100 p-3"><div className="flex items-center"><span className="text-sm font-medium">{project.name}</span><span className="ml-auto text-xs text-slate-400">{project.code}</span></div><p className="mt-1 text-xs text-slate-400">{project.memberCount} 位成员 · {project.taskCount} 个任务</p></div>)}{!team.projects.length&&<p className="py-8 text-center text-sm text-slate-400">暂时没有可访问的项目</p>}</div></section></div></div>;
}

function Projects({team}:{team:TeamDetail}){return <section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h3 className="font-semibold">团队项目</h3><p className="mt-0.5 text-xs text-slate-400">普通成员只会看到单独授权的项目</p></div>{team.permissions.canCreateProject&&<Link href="/projects" className="secondary-button"><Plus size={16}/>新建项目</Link>}</div><div className="divide-y divide-slate-100">{team.projects.map(project=><div key={project.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center"><span className="grid size-10 place-items-center rounded-xl bg-blue-50 text-blue-600"><FolderKanban size={19}/></span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><b className="text-sm">{project.name}</b><span className="rounded bg-slate-100 px-1.5 py-0.5 text-[10px] text-slate-500">{project.code}</span></div><p className="mt-1 truncate text-xs text-slate-400">{project.description||"暂无说明"}</p></div><div className="flex gap-4 text-xs text-slate-500"><span>{project.memberCount} 位成员</span><span>{project.taskCount} 个任务</span></div></div>)}{!team.projects.length&&<Empty title="暂无可访问项目" description="团队身份不会自动授予项目权限。"/>}</div></section>}

function Members({team,reload}:{team:TeamDetail;reload:()=>Promise<void>}){
  const [query,setQuery]=useState(""),[busy,setBusy]=useState(""),[error,setError]=useState("");
  const filtered=team.members.filter(x=>`${x.name}${x.phone}${x.roleLabel}`.toLowerCase().includes(query.toLowerCase()));
  async function change(member:TeamDetail["members"][number],role:Role){setBusy(member.id);setError("");try{await jsonRequest(`/api/teams/${team.id}/members/${member.id}`,{method:"PATCH",body:JSON.stringify({role})});await reload();}catch(e){setError(e instanceof Error?e.message:"修改失败");}finally{setBusy("");}}
  async function remove(member:TeamDetail["members"][number]){if(!window.confirm(`确认将“${member.name}”移出团队？其项目权限不会自动删除。`))return;setBusy(member.id);try{await jsonRequest(`/api/teams/${team.id}/members/${member.id}`,{method:"DELETE"});await reload();}catch(e){setError(e instanceof Error?e.message:"移除失败");}finally{setBusy("");}}
  return <section className="card overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 px-5 py-4 sm:flex-row sm:items-center"><div><h3 className="font-semibold">{team.members.length} 位成员</h3><p className="mt-0.5 text-xs text-slate-400">团队身份与项目成员权限相互独立</p></div><div className="relative sm:ml-auto"><Search className="absolute left-3 top-2.5 text-slate-400" size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} className="h-9 w-full rounded-xl border border-slate-200 bg-white pl-9 pr-3 text-sm outline-none focus:border-blue-400 sm:w-64" placeholder="搜索成员"/></div></div>{error&&<div className="p-4"><ErrorBox message={error}/></div>}<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-slate-100 bg-slate-50/70 text-xs text-slate-400"><th className="px-5 py-3 font-medium">成员</th><th className="px-4 py-3 font-medium">手机号</th><th className="px-4 py-3 font-medium">团队角色</th><th className="px-4 py-3 font-medium">加入时间</th><th className="px-5 py-3"></th></tr></thead><tbody>{filtered.map(member=>{const editable=team.permissions.canManage&&member.role!=="OWNER"&&!(team.currentRole==="ADMIN"&&member.role==="ADMIN");return <tr key={member.id} className="border-b border-slate-100 last:border-0"><td className="px-5 py-3"><div className="flex items-center gap-3"><Avatar name={member.name} color={member.avatarColor}/><span className="text-sm font-medium">{member.name}</span></div></td><td className="px-4 py-3 text-sm text-slate-500">{member.phone}</td><td className="px-4 py-3">{editable?<select disabled={busy===member.id} value={member.role} onChange={e=>void change(member,e.target.value as Role)} className="rounded-lg border border-slate-200 bg-white px-2 py-1.5 text-xs outline-none"><option value="MEMBER">团队成员</option><option value="GUEST">访客</option>{team.permissions.canInviteAdmin&&<option value="ADMIN">团队管理员</option>}</select>:<span className={`rounded-full px-2.5 py-1 text-xs ${roleClass[member.role]}`}>{member.roleLabel}</span>}</td><td className="px-4 py-3 text-sm text-slate-500">{new Date(member.joinedAt).toLocaleDateString("zh-CN")}</td><td className="px-5 py-3 text-right">{editable&&<button disabled={busy===member.id} onClick={()=>void remove(member)} aria-label="移除成员" className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 size={16}/></button>}</td></tr>})}</tbody></table></div></section>;
}

function Invites({team,reload,onNew}:{team:TeamDetail;reload:()=>Promise<void>;onNew:()=>void}){
  const [busy,setBusy]=useState(""),[error,setError]=useState(""),[freshUrl,setFreshUrl]=useState(""),[copiedId,setCopiedId]=useState("");
  async function reset(id:string,copyAfter=false){setBusy(id);setError("");try{const data=await jsonRequest<{invite:{url:string}}>(`/api/teams/${team.id}/invites/${id}/reset`,{method:"POST"});setFreshUrl(data.invite.url);if(copyAfter){await copyText(data.invite.url);setCopiedId(id);window.setTimeout(()=>setCopiedId(""),1800);}await reload();}catch(e){setError(e instanceof Error?e.message:"重置失败");}finally{setBusy("");}}
  async function copy(invite:TeamDetail["invites"][number]){setBusy(invite.id);setError("");try{if(invite.url){await copyText(invite.url);setCopiedId(invite.id);window.setTimeout(()=>setCopiedId(""),1800);}else{await reset(invite.id,true);}}catch(e){setError(e instanceof Error?e.message:"复制失败，请稍后重试");}finally{setBusy("");}}
  async function revoke(id:string){if(!window.confirm("撤销后原邀请链接将立即失效，确认继续？"))return;setBusy(id);try{await jsonRequest(`/api/teams/${team.id}/invites/${id}`,{method:"DELETE"});await reload();}catch(e){setError(e instanceof Error?e.message:"撤销失败");}finally{setBusy("");}}
  if(!team.permissions.canManage)return <Empty title="无权查看邀请" description="只有团队所有者和管理员可以管理邀请链接。"/>;
  return <section className="space-y-4">{freshUrl&&<CopyNotice url={freshUrl} onClose={()=>setFreshUrl("")}/>} {error&&<ErrorBox message={error}/>}<div className="card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h3 className="font-semibold">邀请链接</h3><p className="mt-0.5 text-xs text-slate-400">有效链接可随时复制；旧版链接会在首次复制时安全重置</p></div><button onClick={onNew} className="primary-button"><UserPlus size={16}/>新建邀请</button></div><div className="overflow-x-auto"><table className="w-full min-w-[880px] text-left"><thead><tr className="bg-slate-50/70 text-xs text-slate-400"><th className="px-5 py-3 font-medium">邀请</th><th className="px-4 py-3 font-medium">角色</th><th className="px-4 py-3 font-medium">使用情况</th><th className="px-4 py-3 font-medium">有效期</th><th className="px-4 py-3 font-medium">状态</th><th className="px-5 py-3"></th></tr></thead><tbody>{team.invites.map(invite=>{const expired=new Date(invite.expiresAt)<=new Date(),full=invite.useCount>=invite.maxUses;const status=invite.revokedAt?"已撤销":expired?"已过期":full?"已用完":"有效";return <tr key={invite.id} className="border-t border-slate-100"><td className="max-w-[320px] px-5 py-3"><p className="truncate font-mono text-sm text-slate-700">{invite.url||`${invite.prefix}••••••`}</p><p className="mt-0.5 text-xs text-slate-400">{invite.createdBy} 创建{!invite.url&&status==="有效"?" · 复制时将生成新链接":""}</p></td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-xs ${roleClass[invite.role]}`}>{invite.roleLabel}</span></td><td className="px-4 py-3 text-sm text-slate-500">{invite.useCount} / {invite.maxUses}</td><td className="px-4 py-3 text-sm text-slate-500">{new Date(invite.expiresAt).toLocaleString("zh-CN",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"})}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-xs ${status==="有效"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{status}</span></td><td className="px-5 py-3"><div className="flex justify-end gap-1"><button disabled={busy===invite.id||status!=="有效"} onClick={()=>void copy(invite)} title={invite.url?"复制邀请链接":"生成并复制新链接"} className="rounded-lg p-2 text-slate-400 hover:bg-blue-50 hover:text-blue-600 disabled:cursor-not-allowed disabled:opacity-40">{copiedId===invite.id?<Check size={16}/>:<Clipboard size={16}/>}</button><button disabled={busy===invite.id} onClick={()=>void reset(invite.id)} title="重置链接" className="rounded-lg p-2 text-slate-400 hover:bg-blue-50 hover:text-blue-600"><RefreshCw className={busy===invite.id?"animate-spin":""} size={16}/></button>{!invite.revokedAt&&<button disabled={busy===invite.id} onClick={()=>void revoke(invite.id)} title="撤销链接" className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 size={16}/></button>}</div></td></tr>})}</tbody></table>{!team.invites.length&&<Empty title="暂无邀请链接" description="创建邀请链接后，可以分享给希望加入团队的成员。"/>}</div></div></section>;
}

function InviteModal({team,onClose,onCreated}:{team:TeamDetail;onClose:()=>void;onCreated:()=>void}){
  const [role,setRole]=useState<Role>("MEMBER"),[maxUses,setMaxUses]=useState(50),[url,setUrl]=useState(""),[copied,setCopied]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState("");
  async function create(){setLoading(true);setError("");try{const data=await jsonRequest<{invite:{url:string}}>(`/api/teams/${team.id}/invites`,{method:"POST",body:JSON.stringify({role,maxUses})});setUrl(data.invite.url);onCreated();}catch(e){setError(e instanceof Error?e.message:"创建失败");}finally{setLoading(false);}}
  async function copy(){try{await copyText(url);setCopied(true);window.setTimeout(()=>setCopied(false),1600);}catch(e){setError(e instanceof Error?e.message:"复制失败，请手动选择链接复制");}}
  return <Modal title={`邀请加入 ${team.name}`} onClose={onClose} wide><div className="mb-5 grid grid-cols-3 rounded-xl bg-slate-100 p-1 text-sm"><span className="rounded-lg bg-white py-2.5 text-center font-medium shadow-sm">链接邀请</span><span className="py-2.5 text-center text-slate-400">邮箱邀请 · 暂未开放</span><span className="py-2.5 text-center text-slate-400">组织选择 · 暂未开放</span></div><div className="rounded-xl bg-blue-50/70 p-4 text-sm text-slate-600">邀请成员加入团队。链接将在创建后 7 天过期，加入团队不会自动获得项目权限。</div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="团队角色"><select className="field" value={role} onChange={e=>setRole(e.target.value as Role)}><option value="MEMBER">团队成员</option><option value="GUEST">访客</option>{team.permissions.canInviteAdmin&&<option value="ADMIN">团队管理员</option>}</select></Field><Field label="人数上限"><input className="field" type="number" min={1} max={50} value={maxUses} onChange={e=>setMaxUses(Math.max(1,Math.min(50,Number(e.target.value))))}/></Field></div>{url?<div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50/70 p-3"><p className="mb-2 text-xs font-medium text-emerald-700">邀请链接已生成，可立即复制，也可稍后在“待定邀请”中再次复制</p><div className="flex flex-col gap-2 sm:flex-row sm:items-center"><Link2 className="hidden shrink-0 text-slate-400 sm:block" size={18}/><input readOnly onFocus={e=>e.currentTarget.select()} value={url} className="min-w-0 flex-1 rounded-lg border border-emerald-100 bg-white px-3 py-2 text-sm outline-none"/><button onClick={()=>void copy()} className="primary-button shrink-0 justify-center">{copied?<Check size={16}/>:<Clipboard size={16}/>} {copied?"已复制":"复制链接"}</button></div></div>:<button disabled={loading} onClick={()=>void create()} className="primary-button mt-5 w-full justify-center">{loading?<LoaderCircle className="animate-spin" size={17}/>:<Link2 size={17}/>}生成邀请链接</button>}{error&&<div className="mt-4"><ErrorBox message={error}/></div>}</Modal>;
}

function Roles(){const rows=[{role:"团队所有者",tag:"OWNER",desc:"管理团队、管理员、邀请、成员与所有团队项目",tone:"bg-orange-50 text-orange-700"},{role:"团队管理员",tag:"ADMIN",desc:"管理普通成员与访客、创建项目和普通邀请",tone:"bg-violet-50 text-violet-700"},{role:"团队成员",tag:"MEMBER",desc:"查看团队信息，只能进入单独授权的项目",tone:"bg-emerald-50 text-emerald-700"},{role:"访客",tag:"GUEST",desc:"有限查看团队信息，只能进入单独授权的项目",tone:"bg-slate-100 text-slate-600"}];return <div className="card overflow-hidden"><div className="border-b border-slate-100 p-5"><h3 className="font-semibold">角色与权限</h3><p className="mt-1 text-sm text-slate-500">团队角色负责组织管理，项目角色负责具体项目访问。</p></div><div className="divide-y divide-slate-100">{rows.map(row=><div key={row.tag} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center"><span className={`w-fit rounded-full px-2.5 py-1 text-xs ${row.tone}`}>{row.role}</span><p className="flex-1 text-sm text-slate-600">{row.desc}</p><code className="text-xs text-slate-400">{row.tag}</code></div>)}</div></div>}
function Settings({team}:{team:TeamDetail}){return <div className="card p-5"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-slate-100 text-slate-500"><Settings2 size={19}/></span><div><h3 className="font-semibold">团队设置</h3><p className="mt-1 text-sm text-slate-500">团队资料编辑、所有权转让与删除将在后续版本开放。</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-slate-100 p-4"><p className="text-xs text-slate-400">团队名称</p><p className="mt-1 text-sm font-medium">{team.name}</p></div><div className="rounded-xl border border-slate-100 p-4"><p className="text-xs text-slate-400">当前身份</p><p className="mt-1 text-sm font-medium">{team.currentRoleLabel}</p></div></div></div>}

function Modal({title,onClose,children,wide=false}:{title:string;onClose:()=>void;children:React.ReactNode;wide?:boolean}){return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/30 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div role="dialog" aria-modal="true" aria-label={title} className={`max-h-[90vh] w-full overflow-y-auto rounded-2xl border border-slate-200 bg-white p-5 shadow-2xl ${wide?"max-w-3xl":"max-w-lg"}`}><div className="mb-5 flex items-center"><h3 className="text-lg font-semibold">{title}</h3><button onClick={onClose} aria-label="关闭" className="ml-auto rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={19}/></button></div>{children}</div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-sm font-medium">{label}</span>{children}</label>}
function Avatar({name,color}:{name:string;color:string}){return <span className="grid size-8 shrink-0 place-items-center rounded-full text-xs font-semibold text-white ring-2 ring-white" style={{backgroundColor:color}}>{name.slice(-1)}</span>}
function ErrorBox({message}:{message:string}){return <div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{message}</div>}
function Loading(){return <div className="grid min-h-72 place-items-center"><LoaderCircle className="animate-spin text-blue-600" size={28}/></div>}
function Empty({title,description,action}:{title:string;description:string;action?:React.ReactNode}){return <div className="grid min-h-48 place-items-center p-8 text-center"><div><span className="mx-auto grid size-11 place-items-center rounded-xl bg-slate-100 text-slate-400"><Building2 size={20}/></span><h3 className="mt-3 font-semibold">{title}</h3><p className="mt-1 text-sm text-slate-400">{description}</p>{action&&<div className="mt-4 flex justify-center">{action}</div>}</div></div>}
function CopyNotice({url,onClose}:{url:string;onClose:()=>void}){const [copied,setCopied]=useState(false),[error,setError]=useState("");return <div className="card border-emerald-200 bg-emerald-50 p-4"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 shrink-0 text-emerald-600" size={19}/><div className="min-w-0 flex-1"><p className="text-sm font-medium text-emerald-800">新邀请链接已生成</p><p className="mt-1 truncate text-xs text-emerald-700">{url}</p>{error&&<p className="mt-1 text-xs text-rose-600">{error}</p>}</div><button onClick={()=>void copyText(url).then(()=>setCopied(true)).catch(e=>setError(e instanceof Error?e.message:"复制失败"))} className="secondary-button shrink-0">{copied?<Check size={15}/>:<Clipboard size={15}/>} {copied?"已复制":"复制"}</button><button onClick={onClose} className="p-2 text-emerald-700"><X size={17}/></button></div></div>}
